runtime: go
api_version: go1.8
handlers:
- url: /.*
  script: _go_app
instance_class: F2
automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: automatic # default value
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
